title: Neha Hulkund
url: "hulkund.github.io"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/hulkund.github.io"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "cv.pdf"
 - name: "Contact"
   link: mailto:nhulkund@mit.edu

#Build settings
remote_theme: samarsault/texture
